#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dsystem_socket=/run/dbus/system_bus_socket \
    -Dsystem_pid_file=/run/dbus/pid \
    -Ddoxygen_docs=disabled \
    build

ninja -C build
ninja -C build install

mkdir -p "$1/etc/sv/dbus"
cp -f dbus.run "$1/etc/sv/dbus/run"
ln -sf /run/runit/supervise.dbus "$1/etc/sv/dbus/supervise"
