#!/bin/sh -e

set -x

export DESTDIR="$1"

# rust_std is not (yet?) supported by muon, and we should try
# to avoid a hard rust dependency here if possible.
sed '/rust_std=2021/d' meson.build > _
mv -f _ meson.build

# To prevent the need for users to fork the mesa package to add
# libglvnd support, the below code checks for its availability
# and enables it if present. ie: install glvnd, rebuild mesa.
pkg-config --exists libglvnd || glvnd_enabled=false


meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms=x11 \
    -Dglx=auto \
    -Degl=enabled \
    -Dgbm=enabled \
    -Dopengl=true \
    -Dgles2=enabled \
    -Dgallium-drivers=iris,llvmpipe \
    -Dvulkan-drivers=intel \
    -Dgallium-va=disabled \
    -Dllvm=enabled \
    -Dshared-llvm=enabled \
    -Dlibunwind=enabled \
    -Db_lto=true \
    -Dvalgrind=disabled \
    -Dzstd=enabled \
    -Dglvnd="${glvnd_enabled:-true}" \
output

ninja -C output
ninja -C output install
