#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --disable-systemd \
    --enable-library \
    --disable-manpages \
    --disable-obex \
    --with-udevdir=/etc/udev

make
make DESTDIR="$1" install

mkdir -p "$1/etc/sv/bluetoothd"
cp -f bluetoothd.run "$1/etc/sv/bluetoothd/run"
ln -sf /run/runit/supervise.bluetoothd "$1/etc/sv/bluetoothd/supervise"
