#!/bin/sh -e

export DESTDIR="$1"

#patch -p1 < rootless_modesetting.patch
#patch -p1 < xorg-pixmap-fix.patch

diff --git a/include/scrnintstr.h b/include/scrnintstr.h
index 71ef762ea0..a51144cbcc 100644
--- a/include/scrnintstr.h
+++ b/include/scrnintstr.h
@@ -620,6 +620,8 @@ typedef struct _Screen {
     SetScreenPixmapProcPtr SetScreenPixmap;
     NameWindowPixmapProcPtr NameWindowPixmap;
 
+    PixmapPtr pScratchPixmap;   /* scratch pixmap "pool" (unused / NULL in modern servers) */
+
     unsigned int totalPixmapSize;
 
     MarkWindowProcPtr MarkWindow;


# Disable tests.
: > test/meson.build

# Make meson_options.txt muon compatible.
sed -E "/boolean/s/'(true|false)'/\1/" meson_options.txt > _
mv -f _ meson_options.txt

meson setup \
    -Dwarning_level=2 \
    -Dprefix='/usr' \
    -Dlocalstatedir='/var' \
    -Dsystemd_logind=false \
    -Dglx=true \
    -Ddri1=true \
    -Ddri2=true \
    -Ddri3=true \
    -Dglamor=true \
    -Dxorg=true \
    -Dxephyr=false \
    -Dxdmcp=true \
    -Ddefault_font_path=/usr/share/fonts \
    output

ninja -C output
ninja -C output install
