#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < musl.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 

cmake --build   build
cmake --install build
