#!/bin/bash -uxe
export DESTDIR="$1"

cmake -B build -G Ninja \
	-D BUILD_TYPE=Release \
	-D CMAKE_BUILD_TYPE=Release \
	-D CMAKE_INSTALL_PREFIX=/usr \
	-D RUN_TEST_SUITE=ON \
	-DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
	-Wno-dev 

ninja -j4 -C build
ninja -C build install
